// <auto-generated />
using System;
using AnalistaFinanziarioIA.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalistaFinanziarioIA.Infrastructure.Migrations
{
    [DbContext(typeof(AnalistaFinanziarioDbContext))]
    [Migration("20260406151351_AddDefaultDateToTitoli")]
    partial class AddDefaultDateToTitoli
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.AnalisiFinanziaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAnalisi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PrezzoTarget")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Raccomandazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Risultato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAnalisi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TitoloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TitoloId");

                    b.ToTable("Analisi", (string)null);
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.AssetPortafoglio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrezzoMedioCarico")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QuantitaTotale")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TitoloId")
                        .HasColumnType("int");

                    b.Property<Guid>("UtenteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TitoloId");

                    b.HasIndex("UtenteId");

                    b.ToTable("AssetsPortafoglio", (string)null);
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.Dividendo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetPortafoglioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ImportoLordo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TasseTrattenute")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Valuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetPortafoglioId");

                    b.ToTable("Dividendi", (string)null);
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.QuotazioneStorica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrezzoApertura")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrezzoChiusura")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrezzoMassimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrezzoMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TitoloId")
                        .HasColumnType("int");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TitoloId", "Data")
                        .IsUnique();

                    b.ToTable("QuotazioniStoriche", (string)null);
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.Titolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Mercato")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Settore")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Simbolo")
                        .IsUnique();

                    b.ToTable("Titoli", (string)null);
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.Transazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetPortafoglioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Commissioni")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrezzoUnita")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Quantita")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TassoCambio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetPortafoglioId");

                    b.ToTable("Transazioni", (string)null);
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.Utente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValutaBase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utenti", (string)null);
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.AnalisiFinanziaria", b =>
                {
                    b.HasOne("AnalistaFinanziarioIA.Core.Models.Titolo", "Titolo")
                        .WithMany("Analisi")
                        .HasForeignKey("TitoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Titolo");
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.AssetPortafoglio", b =>
                {
                    b.HasOne("AnalistaFinanziarioIA.Core.Models.Titolo", "Titolo")
                        .WithMany()
                        .HasForeignKey("TitoloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnalistaFinanziarioIA.Core.Models.Utente", null)
                        .WithMany("Assets")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Titolo");
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.Dividendo", b =>
                {
                    b.HasOne("AnalistaFinanziarioIA.Core.Models.AssetPortafoglio", null)
                        .WithMany("Dividendi")
                        .HasForeignKey("AssetPortafoglioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.QuotazioneStorica", b =>
                {
                    b.HasOne("AnalistaFinanziarioIA.Core.Models.Titolo", "Titolo")
                        .WithMany("QuotazioniStoriche")
                        .HasForeignKey("TitoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Titolo");
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.Transazione", b =>
                {
                    b.HasOne("AnalistaFinanziarioIA.Core.Models.AssetPortafoglio", null)
                        .WithMany("Transazioni")
                        .HasForeignKey("AssetPortafoglioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.AssetPortafoglio", b =>
                {
                    b.Navigation("Dividendi");

                    b.Navigation("Transazioni");
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.Titolo", b =>
                {
                    b.Navigation("Analisi");

                    b.Navigation("QuotazioniStoriche");
                });

            modelBuilder.Entity("AnalistaFinanziarioIA.Core.Models.Utente", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
